#!/usr/bin/env python3
"""Publish a Business Conspect report using the fast-path pipeline.

Steps:
1) Validate report.md
2) Ensure a minimal index.html exists for the report
3) Update the global index (index.html + index.json)
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import subprocess
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[2]
VALIDATOR_PATH = ROOT / "business-conspect/scripts/validate_report.py"
INDEX_UPDATER_PATH = ROOT / "business-conspect/scripts/update_index.py"
ROOT_INDEX_PATH = ROOT / "business-conspect/index.html"


TITLE_PREFIX = "# Business Conspect — "


def _read_report_title(report_path: Path) -> str:
    if not report_path.is_file():
        return "Business Conspect Report"
    for line in report_path.read_text(encoding="utf-8").splitlines():
        if line.startswith(TITLE_PREFIX):
            return line.replace("# ", "").strip()
    return "Business Conspect Report"


def _read_website(report_path: Path) -> str:
    if not report_path.is_file():
        return ""
    in_metadata = False
    for line in report_path.read_text(encoding="utf-8").splitlines():
        if line.strip() == "## 1) Report Metadata":
            in_metadata = True
            continue
        if in_metadata and line.startswith("## "):
            break
        if in_metadata and line.strip().startswith("- Website:"):
            return line.split(":", 1)[1].strip()
    return ""


def _ensure_index_html(report_dir: Path, report_path: Path) -> Path:
    index_path = report_dir / "index.html"
    if index_path.exists():
        return index_path

    title = _read_report_title(report_path)
    website = _read_website(report_path)

    try:
        rel_index = ROOT_INDEX_PATH.relative_to(report_dir)
    except ValueError:
        rel_index = Path("../../index.html")

    website_line = ""
    if website:
        website_line = f"<p><strong>Website:</strong> <a href=\"{website}\">{website}</a></p>"

    content = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{title}</title>
    <link rel="canonical" href="report.md" />
  </head>
  <body style="font-family: Arial, sans-serif; padding: 2rem; max-width: 900px; margin: 0 auto;">
    <main>
      <h1>{title}</h1>
      <p>This is a minimal report page generated by the fast-path publisher.</p>
      <p>The canonical report is <a href="report.md">report.md</a>.</p>
      {website_line}
      <p><a href="{rel_index}">Back to Business Conspect index</a></p>
      <p style="color: #666; font-size: 0.9rem;">Generated at {datetime.utcnow().isoformat()}Z</p>
    </main>
  </body>
</html>
"""
    index_path.write_text(content, encoding="utf-8")
    return index_path


def _run(cmd: list[str], *, label: str) -> int:
    print(f"[run] {label}: {' '.join(cmd)}")
    result = subprocess.run(cmd, check=False)
    return result.returncode


def publish(report_dir: Path) -> int:
    report_dir = report_dir.resolve()
    report_path = report_dir / "report.md"

    if not VALIDATOR_PATH.is_file():
        print(f"Missing validator: {VALIDATOR_PATH}", file=sys.stderr)
        return 1
    if not INDEX_UPDATER_PATH.is_file():
        print(f"Missing index updater: {INDEX_UPDATER_PATH}", file=sys.stderr)
        return 1

    code = _run([sys.executable, str(VALIDATOR_PATH), str(report_path)], label="validate")
    if code != 0:
        print("Validation failed; aborting publish.", file=sys.stderr)
        return code

    index_path = _ensure_index_html(report_dir, report_path)
    print(f"[ok] index.html ready: {index_path}")

    code = _run([sys.executable, str(INDEX_UPDATER_PATH)], label="update index")
    if code != 0:
        print("Index update failed.", file=sys.stderr)
        return code

    print("[ok] Publish completed.")
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Publish a report: validate, ensure index.html, update index."
    )
    parser.add_argument(
        "report_dir",
        help="Path to a report directory containing report.md.",
    )
    return parser


def main(argv: list[str]) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    return publish(Path(args.report_dir))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))

